### ISSUE TITLE
python 3.2 failure due to using a coverage version that no longer supports it

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [mfalesni/python-kwargify#8]
since the world is dropping support for python 3.2, i suggest to drop it as well,

the alternative is pinning of compatible versions

**Comment by mfalesni** [comment]
Yes, I was looking at it, seems python 3.2 does not support the `u''` whereas all other 3.x pythons support it as a fallback.

**Comment by RonnyPfannschmidt** [comment]
it was added as feature in 3.3 to support single-source setups that need unicode literals
